Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -37,7 +37,15 @@ jobs:
       - name: Build Docker Image
         run: docker-compose -f compose.yaml build
 
-     
+      - name: Verify Docker image build
+        run: |
+         IMAGE_ID=$(docker images -q soumyanaveen/yourimage:latest)
+         if [ -n "$IMAGE_ID" ]; then
+          echo "Docker image built successfully."
+         else
+          echo "Error: Docker image build failed."
+          exit 1
+          fi
 
       - name: Update Docker Compose file
         id: update-compose
